---
run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    # deprecated
    - ifshort
    - exhaustivestruct
    - golint
    - structcheck
    - scopelint
    - interfacer
    - varcheck
    - maligned
    - deadcode
    - nosnakecase
    # need config
    - forbidigo
    # don't need it
    - varnamelen
    - depguard
linters-settings:
  lll:
    line-length: 120
  gofumpt:
    extra-rules: true
    module-path: "github.com/EveKeehl/go-learn/lesson1"

issues:
  exclude-rules:
    # There will be some ToDos.
    - linters:
        - godox
      text: "TODO"

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
